import type { Lesson } from "@/domain/types";

/**
 * Boxing lessons for Levels 1 to 6.
 * Written for an orthodox (left foot forward) boxer; southpaws mirror everything.
 * Everything is solo practice at home: shadowboxing or a bag. No partner or sparring drills.
 * DRAFT: must be reviewed by a qualified boxing coach before public launch.
 */

const GENERAL_SAFETY = "Warm up first and keep the movement controlled.";
const SOLO_DEFENSE = "Practise this alone, as shadowboxing. Never ask a friend to hit you; that needs a coach and proper gear.";
const CLEAR_SPACE = "Clear the space around you and check the floor. Do not train in socks on a slippery floor.";

export const BOXING_LESSONS: Lesson[] = [
  // ---------------- LEVEL 1: FUNDAMENTALS ----------------
  {
    id: "boxing-stance",
    sport: "boxing",
    level: 1,
    title: "Fighting Stance",
    summary: "The base every punch and step comes from.",
    whatItIs: "A balanced, side-on position that lets you attack, defend and move without falling off balance.",
    whenToUse: "All the time. You return to your stance after every punch and every step.",
    mechanics: [
      "Feet about shoulder-width apart, lead foot forward (left foot if you are right-handed).",
      "Rear foot turned out about 45 degrees, rear heel slightly raised.",
      "Knees softly bent, weight spread evenly between both feet.",
      "Body turned slightly side-on so your lead shoulder points at the target.",
    ],
    commonMistakes: [
      "Feet in one straight line, which makes you easy to push over.",
      "Standing square with both feet level.",
      "Locked, straight knees.",
    ],
    safetyNotes: [GENERAL_SAFETY, "If your knees or hips hurt in the stance, widen it slightly and reduce the bend."],
    quiz: [
      {
        id: "stance-q1",
        question: "In an orthodox stance, which foot is in front?",
        options: ["Right foot", "Left foot", "Both level"],
        correctIndex: 1,
        explanation: "Orthodox boxers lead with the left foot. Southpaws lead with the right.",
      },
      {
        id: "stance-q2",
        question: "Why should your feet not be in one straight line?",
        options: ["It looks wrong", "You lose balance easily", "It slows your jab"],
        correctIndex: 1,
        explanation: "Feet on one line give you no base, so a small push or step can tip you over.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-guard",
    sport: "boxing",
    level: 1,
    title: "The Guard",
    summary: "Where your hands live when you are not punching.",
    whatItIs: "Hand and elbow positions that protect your head and body while keeping you ready to punch.",
    whenToUse: "Always. Every punch starts from the guard and returns to it.",
    mechanics: [
      "Rear fist touches your cheek or chin.",
      "Lead fist at eye level, slightly in front of your face.",
      "Elbows tucked in to cover the ribs.",
      "Chin tucked down, eyes looking up at the target.",
    ],
    commonMistakes: ["Dropping the hands when tired.", "Chin up in the air.", "Elbows flaring out wide."],
    safetyNotes: [GENERAL_SAFETY, "Relax your shoulders; holding the guard tense causes neck strain."],
    quiz: [
      {
        id: "guard-q1",
        question: "Where should your rear fist be in guard?",
        options: ["At your hip", "Touching your cheek or chin", "Stretched forward"],
        correctIndex: 1,
        explanation: "The rear hand protects the chin and is loaded for the cross.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-step-drag",
    sport: "boxing",
    level: 1,
    title: "Forward and Backward Movement",
    summary: "Step and drag: move without crossing your feet.",
    whatItIs: "The basic boxing step. The foot nearest the direction moves first, the other follows the same distance.",
    whenToUse: "Closing distance to attack or creating distance to stay safe.",
    mechanics: [
      "Forward: push off the rear foot, step the lead foot forward a small amount, then bring the rear foot the same amount.",
      "Backward: push off the lead foot, step the rear foot back, then bring the lead foot back.",
      "Keep the stance width the same before and after the step.",
      "Small steps. Guard stays up.",
    ],
    commonMistakes: ["Crossing or bringing the feet together.", "Big lunging steps.", "Bouncing up and down."],
    safetyNotes: [GENERAL_SAFETY, "Check the floor behind you before stepping backward."],
    quiz: [
      {
        id: "step-q1",
        question: "Moving forward, which foot steps first?",
        options: ["Rear foot", "Lead foot", "Either"],
        correctIndex: 1,
        explanation: "The foot nearest the direction you are going moves first.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-lateral",
    sport: "boxing",
    level: 1,
    title: "Lateral Movement",
    summary: "Moving left and right while staying balanced.",
    whatItIs: "Side steps that move you off the centre line without crossing your feet.",
    whenToUse: "Getting out of the way of forward pressure and finding new angles.",
    mechanics: [
      "To your left: lead foot steps left first, rear foot follows.",
      "To your right: rear foot steps right first, lead foot follows.",
      "Stay on the balls of your feet with knees bent.",
    ],
    commonMistakes: ["Crossing the feet.", "Leaning the head to the side instead of moving the feet."],
    safetyNotes: [GENERAL_SAFETY],
    quiz: [
      {
        id: "lateral-q1",
        question: "Moving to your right in an orthodox stance, which foot moves first?",
        options: ["Lead (left) foot", "Rear (right) foot"],
        correctIndex: 1,
        explanation: "The foot nearest the direction of travel moves first.",
      },
    ],
    minutes: 3,
  },

  // ---------------- LEVEL 2: BASIC STRIKES ----------------
  {
    id: "boxing-jab",
    sport: "boxing",
    level: 2,
    title: "Jab (1)",
    summary: "Your fastest, safest punch, thrown with the lead hand.",
    whatItIs: "A straight punch with the lead hand. It measures distance, sets up other punches and keeps opponents back.",
    whenToUse: "To start combinations, to judge distance and to interrupt an opponent who is moving in.",
    mechanics: [
      "From guard, extend the lead hand straight out from the chin.",
      "Rotate the fist so the palm faces down at the end.",
      "Rear hand stays on the chin.",
      "Bring the hand straight back to guard along the same line.",
    ],
    commonMistakes: [
      "Dropping the hand before or after the punch.",
      "Pulling the rear hand away from the chin.",
      "Locking the elbow at full extension.",
    ],
    safetyNotes: [GENERAL_SAFETY, "Stop just short of full extension to protect your elbow when shadowboxing."],
    quiz: [
      {
        id: "jab-q1",
        question: "What number is the jab in boxing callouts?",
        options: ["1", "2", "3"],
        correctIndex: 0,
        explanation: "Jab = 1, cross = 2, lead hook = 3, rear hook = 4, lead uppercut = 5, rear uppercut = 6.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-cross",
    sport: "boxing",
    level: 2,
    title: "Cross (2)",
    summary: "The straight power punch from the rear hand.",
    whatItIs: "A straight punch from the rear hand, powered by turning the rear foot, hip and shoulder.",
    whenToUse: "After a jab, or as a counter when the opponent's guard opens.",
    mechanics: [
      "Pivot on the ball of the rear foot, turning the heel out.",
      "Rotate the hips and rear shoulder forward.",
      "Extend the rear hand straight from the chin; palm down at the end.",
      "Lead hand stays up to protect your face, then the rear hand returns to the chin.",
    ],
    commonMistakes: ["Arm-only punching with no hip turn.", "Leaning too far forward.", "Lead hand dropping."],
    safetyNotes: [GENERAL_SAFETY, "Do not over-rotate the knee; the turn comes from the foot and hip together."],
    quiz: [
      {
        id: "cross-q1",
        question: "Where does most of the cross's power come from?",
        options: ["The arm", "Turning the rear foot and hips", "Jumping forward"],
        correctIndex: 1,
        explanation: "Power starts at the rear foot and travels through the hips and shoulder.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-lead-hook",
    sport: "boxing",
    level: 2,
    title: "Lead Hook (3)",
    summary: "A short, curved punch with the lead hand.",
    whatItIs: "A hooking punch thrown with the lead hand, turning the body so the arm travels across in front of you.",
    whenToUse: "At close range, often after a jab-cross when the opponent covers the middle.",
    mechanics: [
      "Elbow raised to about shoulder height, arm bent near 90 degrees.",
      "Pivot the lead foot and turn the hips and shoulders.",
      "The arm moves with the body; it does not swing on its own.",
      "Rear hand stays on the chin.",
    ],
    commonMistakes: ["Winding up (pulling the arm back first).", "Swinging wide with a straight arm.", "Not turning the lead foot."],
    safetyNotes: [GENERAL_SAFETY, "Turn the lead foot with the punch to protect the knee."],
    quiz: [
      {
        id: "lhook-q1",
        question: "What should your lead foot do during a lead hook?",
        options: ["Stay flat and still", "Pivot with the hips", "Step forward"],
        correctIndex: 1,
        explanation: "Pivoting lets the body turn and protects the knee.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-rear-hook",
    sport: "boxing",
    level: 2,
    title: "Rear Hook (4)",
    summary: "The hook from the rear hand.",
    whatItIs: "A hooking punch from the rear side, turning through the rear foot and hips.",
    whenToUse: "At close range, often after a lead hook or when the opponent leans to your rear side.",
    mechanics: [
      "Pivot the rear foot and turn the hips forward.",
      "Rear elbow lifts and the arm stays bent.",
      "Lead hand comes back to protect the chin.",
    ],
    commonMistakes: ["Over-swinging and losing balance.", "Lead hand dropping."],
    safetyNotes: [GENERAL_SAFETY],
    quiz: [
      {
        id: "rhook-q1",
        question: "Which hand guards your chin while you throw the rear hook?",
        options: ["The lead hand", "Neither", "The rear hand"],
        correctIndex: 0,
        explanation: "When the rear hand punches, the lead hand covers the face.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-lead-uppercut",
    sport: "boxing",
    level: 2,
    title: "Lead Uppercut (5)",
    summary: "An upward punch with the lead hand.",
    whatItIs: "A short rising punch thrown with the lead hand by dipping slightly and driving up through the legs.",
    whenToUse: "At close range when the opponent leans forward or covers up high.",
    mechanics: [
      "Dip slightly toward the lead side by bending the knees.",
      "Drive up through the legs and turn the hips.",
      "Fist travels upward, palm facing you, elbow bent.",
    ],
    commonMistakes: ["Dropping the hand low before punching.", "Throwing from too far away."],
    safetyNotes: [GENERAL_SAFETY, "Keep the dip small; deep squats are not needed."],
    quiz: [
      {
        id: "luc-q1",
        question: "Where does an uppercut's power start?",
        options: ["The legs and hips", "The wrist", "The neck"],
        correctIndex: 0,
        explanation: "Like every punch, it starts from the ground up.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-rear-uppercut",
    sport: "boxing",
    level: 2,
    title: "Rear Uppercut (6)",
    summary: "An upward punch with the rear hand.",
    whatItIs: "A short rising punch from the rear hand, turning the rear hip forward.",
    whenToUse: "At close range, often after a lead hook.",
    mechanics: [
      "Dip slightly to the rear side.",
      "Turn the rear foot and hip forward as you rise.",
      "Fist travels upward with the elbow bent; lead hand guards the chin.",
    ],
    commonMistakes: ["Winding the arm down first.", "Leaning back as you throw."],
    safetyNotes: [GENERAL_SAFETY],
    quiz: [
      {
        id: "ruc-q1",
        question: "What is the rear uppercut's number in callouts?",
        options: ["4", "5", "6"],
        correctIndex: 2,
        explanation: "Rear uppercut = 6.",
      },
    ],
    minutes: 3,
  },

  // ---------------- LEVEL 3: COMBINATIONS ----------------
  {
    id: "boxing-one-two",
    sport: "boxing",
    level: 3,
    title: "One-Two (1, 2)",
    summary: "Jab then cross: the most important combination in boxing.",
    whatItIs: "A jab followed straight away by a cross. The jab finds the target and the cross follows it in.",
    whenToUse: "To start an attack, to score clean points, and to set up longer combinations.",
    mechanics: [
      "Throw a sharp jab from your guard.",
      "As the jab comes back, the cross goes out. One hand comes back while the other goes out.",
      "Turn the back foot and hip on the cross, the same as in the cross lesson.",
      "Keep your chin down and your free hand on your face the whole time.",
      "Both hands come back to guard, then step back or to the side.",
    ],
    commonMistakes: [
      "A long pause between the jab and the cross.",
      "Dropping the jab hand while the cross goes out.",
      "Leaning forward and reaching with the cross.",
    ],
    safetyNotes: [GENERAL_SAFETY, "Do not lock your elbows when you punch the air. Stop just short of full reach."],
    quiz: [
      {
        id: "onetwo-q1",
        question: "In a one-two, when does the cross go out?",
        options: ["After a long pause", "As the jab comes back", "Before the jab"],
        correctIndex: 1,
        explanation: "One hand comes back as the other goes out. This keeps the combo fast and keeps one hand near your face.",
      },
      {
        id: "onetwo-q2",
        question: "What should you do after your one-two?",
        options: ["Stand still and watch", "Drop your hands to rest", "Hands back to guard, then move"],
        correctIndex: 2,
        explanation: "After punching, return to guard and move so you are not an easy target.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-jab-cross-hook",
    sport: "boxing",
    level: 3,
    title: "Jab, Cross, Lead Hook (1, 2, 3)",
    summary: "Add the lead hook to the one-two.",
    whatItIs: "A three-punch combination: jab, cross, then a short lead hook.",
    whenToUse: "When the opponent covers the middle after your one-two, the hook goes around the side of the guard.",
    mechanics: [
      "Throw a clean one-two.",
      "The cross turns your hips to the left. Turning them back to the right powers the lead hook.",
      "Rear hand comes back to your chin before the hook lands.",
      "Keep the hook short: elbow up, arm bent, turn on the front foot.",
    ],
    commonMistakes: [
      "Pulling the lead arm back to wind up the hook.",
      "Swinging the hook wide with a straight arm.",
      "Leaning over the front foot after the cross, so you lose balance.",
    ],
    safetyNotes: [GENERAL_SAFETY, "Turn the front foot with the hook to protect your knee."],
    quiz: [
      {
        id: "jch-q1",
        question: "Why does the lead hook flow well after the cross?",
        options: ["The cross turns your hips, and turning back powers the hook", "The hook is the slowest punch", "You do not need to turn for a hook"],
        correctIndex: 0,
        explanation: "Each punch turns the hips one way; the next punch uses the turn back.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-body-shots",
    sport: "boxing",
    level: 3,
    title: "Body Shots",
    summary: "Punch to the body by bending your knees.",
    whatItIs: "Punches aimed at the stomach and ribs. You lower your whole body by bending your knees, not by bending forward.",
    whenToUse: "When the opponent keeps the hands high. Body shots tire the opponent and make the hands come down. In callouts, \"body 2\" means a cross to the body.",
    mechanics: [
      "Bend your knees to bring your shoulders down to the target.",
      "Keep your back fairly straight and your eyes up.",
      "Body jab and body cross: straight punches, same as to the head.",
      "Body hook: elbow lower, turn your body into it.",
      "Free hand stays on your chin. Come back up to your normal stance after.",
    ],
    commonMistakes: [
      "Bending forward at the waist with the head out in front.",
      "Dropping the free hand from the face.",
      "Staying low for too long.",
    ],
    safetyNotes: [GENERAL_SAFETY, "Only bend your knees as far as is comfortable. A small drop is enough."],
    quiz: [
      {
        id: "body-q1",
        question: "How do you get low for a body shot?",
        options: ["Bend forward at the waist", "Bend your knees", "Drop your hands"],
        correctIndex: 1,
        explanation: "Bending the knees keeps you balanced and keeps your head out of danger.",
      },
      {
        id: "body-q2",
        question: "What does the callout \"body 2\" mean?",
        options: ["Two jabs", "A cross to the body", "A body hook"],
        correctIndex: 1,
        explanation: "2 is the cross, so \"body 2\" is a cross to the body.",
      },
    ],
    minutes: 4,
  },
  {
    id: "boxing-uppercut-hook-combos",
    sport: "boxing",
    level: 3,
    title: "Uppercut and Hook Combos",
    summary: "Short punches for close range.",
    whatItIs: "Combinations of hooks and uppercuts, such as 6, 3 (rear uppercut, lead hook) or 5, 6, 3.",
    whenToUse: "At close range, when the opponent is near you and covering up.",
    mechanics: [
      "Change hands: a rear-hand punch sets up a lead-hand punch, and the other way round.",
      "Each punch turns the hips one way; the next punch turns them back.",
      "Keep every punch short. Elbows stay bent.",
      "The free hand guards your chin.",
      "Finish the combo with your hands up, then move.",
    ],
    commonMistakes: [
      "Winding the uppercut down from the hip.",
      "Swinging so wide that your hands leave your face.",
      "Leaning in so far that you lose balance.",
    ],
    safetyNotes: [GENERAL_SAFETY, "Keep the dips small. You do not need deep squats."],
    quiz: [
      {
        id: "uphook-q1",
        question: "What does \"6, 3\" mean?",
        options: ["Rear uppercut, then lead hook", "Lead uppercut, then cross", "Rear hook, then jab"],
        correctIndex: 0,
        explanation: "6 is the rear uppercut and 3 is the lead hook.",
      },
      {
        id: "uphook-q2",
        question: "At what range do hooks and uppercuts work best?",
        options: ["Long range", "Close range", "Out of range"],
        correctIndex: 1,
        explanation: "They are short punches. From far away they miss or you have to reach.",
      },
    ],
    minutes: 3,
  },

  // ---------------- LEVEL 4: DEFENSE ----------------
  {
    id: "boxing-block",
    sport: "boxing",
    level: 4,
    title: "Block (High Guard)",
    summary: "Cover up so punches land on your gloves and arms.",
    whatItIs: "Both gloves come up to your forehead and your elbows come together, so punches land on your gloves and forearms.",
    whenToUse: "When punches come fast and you cannot slip or move. Block, then punch back or move away.",
    mechanics: [
      "Bring both gloves up to your forehead, gloves touching your head.",
      "Elbows in, close together, to cover your body.",
      "Chin down. Eyes open, looking between or over your gloves.",
      "Bend your knees a little and stay strong in your stance.",
      "As soon as the punches stop, punch back or move.",
    ],
    commonMistakes: [
      "Closing your eyes or looking at the floor.",
      "Holding the gloves away from your head, so a punch knocks them into your face.",
      "Staying covered and never punching back.",
    ],
    safetyNotes: [GENERAL_SAFETY, SOLO_DEFENSE],
    quiz: [
      {
        id: "block-q1",
        question: "When you block, where should your eyes be?",
        options: ["Closed", "On the floor", "On the opponent, through your gloves"],
        correctIndex: 2,
        explanation: "You must see what comes next, so keep your eyes open and up.",
      },
      {
        id: "block-q2",
        question: "What should you do after blocking?",
        options: ["Stay covered for a long time", "Punch back or move", "Turn your back"],
        correctIndex: 1,
        explanation: "A block is not the end. Answer with punches or move to a safe place.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-slip",
    sport: "boxing",
    level: 4,
    title: "Slip",
    summary: "Move your head just off the line of a straight punch.",
    whatItIs: "A small, quick move of the head to the left or right, so a straight punch goes past you.",
    whenToUse: "Against straight punches: the jab and the cross. Often you slip right against a jab and slip left against a cross.",
    mechanics: [
      "Bend your knees a little and turn your shoulders. Do not bend at the waist.",
      "Slip left: turn your back shoulder forward a little, so your head moves over your front knee.",
      "Slip right: turn your front shoulder in a little, so your head moves just to the right.",
      "Keep it small: just enough for the punch to miss, then back to guard.",
      "Hands stay up and eyes stay on the opponent.",
    ],
    commonMistakes: [
      "Moving the head too far, so you lose balance.",
      "Bending forward at the waist and looking down.",
      "Dropping the hands while slipping.",
    ],
    safetyNotes: [GENERAL_SAFETY, SOLO_DEFENSE],
    quiz: [
      {
        id: "slip-q1",
        question: "Which punches do you slip?",
        options: ["Straight punches like the jab and cross", "Uppercuts", "Body hooks"],
        correctIndex: 0,
        explanation: "A slip moves the head off the straight line a jab or cross travels on.",
      },
      {
        id: "slip-q2",
        question: "How big should a slip be?",
        options: ["As big as possible", "Just enough for the punch to miss", "A full step to the side"],
        correctIndex: 1,
        explanation: "A small slip keeps you balanced and close enough to punch back.",
      },
    ],
    minutes: 4,
  },
  {
    id: "boxing-roll",
    sport: "boxing",
    level: 4,
    title: "Roll (Bob and Weave)",
    summary: "Bend your knees and move under a hook.",
    whatItIs: "You bend your knees and move your head down, across and up, like the letter U, so a hook goes over your head.",
    whenToUse: "Against hooks and other wide punches. It does not work against uppercuts.",
    mechanics: [
      "Bend your knees to go down. Keep your back fairly straight.",
      "Move your head in a U shape: down, across, then up on the other side.",
      "Hands stay up and eyes look forward, not at the floor.",
      "Come up in your stance, ready to punch back.",
    ],
    commonMistakes: [
      "Bending at the waist and looking at the floor.",
      "Going far too low, so you are slow to come up.",
      "Dropping the hands during the roll.",
    ],
    safetyNotes: [GENERAL_SAFETY, "Only go as low as is comfortable for your knees. A small roll is enough.", SOLO_DEFENSE],
    quiz: [
      {
        id: "roll-q1",
        question: "Which punch do you roll under?",
        options: ["A hook", "An uppercut", "A jab to the body"],
        correctIndex: 0,
        explanation: "A hook comes from the side at head height, so you can go under it. Rolling into an uppercut is dangerous.",
      },
      {
        id: "roll-q2",
        question: "What should do most of the work in a roll?",
        options: ["Your neck", "Your waist", "Your knees"],
        correctIndex: 2,
        explanation: "Bend the knees so your head stays up and your eyes stay on the opponent.",
      },
    ],
    minutes: 4,
  },
  {
    id: "boxing-parry",
    sport: "boxing",
    level: 4,
    title: "Parry",
    summary: "Tap a jab away with your back hand.",
    whatItIs: "A small tap with the glove that pushes a straight punch off its line, so it misses your face.",
    whenToUse: "Against the jab. Your back hand catches or taps the opponent's jab.",
    mechanics: [
      "Use your back hand. Keep the move small and close to your face.",
      "Tap the punch a little to the side or down. Do not reach out to meet it.",
      "Your front hand stays up, ready to punch.",
      "Bring the back hand straight back to your chin.",
    ],
    commonMistakes: [
      "Reaching out far to meet the punch.",
      "A big swipe that leaves your face open.",
      "Reacting to every small movement, so fake punches fool you.",
    ],
    safetyNotes: [GENERAL_SAFETY, SOLO_DEFENSE],
    quiz: [
      {
        id: "parry-q1",
        question: "Which hand usually parries the opponent's jab?",
        options: ["Your back hand", "Your front hand", "Both hands"],
        correctIndex: 0,
        explanation: "The back hand is opposite their jab and can tap it away with a small move.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-pull-back",
    sport: "boxing",
    level: 4,
    title: "Pull Back",
    summary: "Lean back just out of reach, then punch back.",
    whatItIs: "You shift your weight onto your back foot so your head moves back, just out of reach of the punch.",
    whenToUse: "Against a jab or cross when you are at the edge of the opponent's reach. Then come forward with a cross.",
    mechanics: [
      "Shift your weight onto your back foot and bend the back knee.",
      "Your head moves back a little, but stays over your back foot.",
      "Chin down, hands up.",
      "Push off the back foot and come forward with a counter, like a cross.",
    ],
    commonMistakes: [
      "Leaning so far back that your head goes behind your back foot.",
      "Lifting the chin as you lean.",
      "Pulling back again and again in a straight line.",
    ],
    safetyNotes: [GENERAL_SAFETY, "Do not lean back so far that you could fall. Keep both feet on the floor.", SOLO_DEFENSE],
    quiz: [
      {
        id: "pullback-q1",
        question: "In a pull back, where does your weight go?",
        options: ["Onto your front foot", "Onto your back foot", "Onto your toes"],
        correctIndex: 1,
        explanation: "Weight on the back foot moves your head back while you stay balanced.",
      },
    ],
    minutes: 3,
  },

  // ---------------- LEVEL 5: COMBINED TRAINING ----------------
  {
    id: "boxing-pivot",
    sport: "boxing",
    level: 5,
    title: "Pivot",
    summary: "Turn on your front foot to change direction.",
    whatItIs: "You stay on the ball of your front foot and swing your back foot around, so your whole body turns, like a door on a hinge.",
    whenToUse: "To get out of the way of an opponent coming forward, to get out of a corner, and to find a new angle.",
    mechanics: [
      "Put your weight on the ball of your front foot.",
      "Swing your back foot around in a quarter circle. Your hips and shoulders turn with it.",
      "Keep your stance width and your guard up.",
      "Finish facing the target again, in a good stance.",
      "Practise a quarter turn one way, then the other way.",
    ],
    commonMistakes: [
      "Turning on the heel instead of the ball of the foot.",
      "Feet coming too close together or crossing.",
      "Dropping the hands while turning.",
    ],
    safetyNotes: [GENERAL_SAFETY, CLEAR_SPACE],
    quiz: [
      {
        id: "pivot-q1",
        question: "Which part of the foot do you pivot on?",
        options: ["The heel of the back foot", "The ball of the front foot", "The whole flat foot"],
        correctIndex: 1,
        explanation: "The ball of the front foot turns easily and keeps the knee safe.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-punch-and-move",
    sport: "boxing",
    level: 5,
    title: "Punch and Move",
    summary: "Never stand still after a combination.",
    whatItIs: "You throw a combination and then move right away: back, or to the side.",
    whenToUse: "After every attack. Moving after punching makes the opponent's counter miss.",
    mechanics: [
      "Throw the combination with good form.",
      "Hands back to guard first.",
      "Then move with the step and drag: back, left or right.",
      "Small steps. Stay in your stance and keep your eyes on the target.",
    ],
    commonMistakes: [
      "Standing still in front of the opponent after punching.",
      "Moving with the hands down.",
      "Crossing the feet when moving.",
    ],
    safetyNotes: [GENERAL_SAFETY, CLEAR_SPACE],
    quiz: [
      {
        id: "punchmove-q1",
        question: "What should you do right after a combination?",
        options: ["Admire it", "Move: back or to the side", "Drop your hands to rest"],
        correctIndex: 1,
        explanation: "Moving after punching keeps you from being hit back.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-defend-and-counter",
    sport: "boxing",
    level: 5,
    title: "Defend and Counter",
    summary: "Defend, then punch back at once.",
    whatItIs: "You use a defensive move and then punch back straight away, while the opponent is still open.",
    whenToUse: "Every time you defend. Good pairs: slip right then cross, slip left then lead hook, roll then 3, 2, block then 3, 2, parry or pull back then cross.",
    mechanics: [
      "Keep the defense small, so you are still close enough to punch.",
      "Punch back at once. Do not wait.",
      "The defense loads the counter: slip left loads the lead hook, slip right loads the cross.",
      "After the counter, back to guard and move.",
    ],
    commonMistakes: [
      "Waiting too long after defending.",
      "Defending with a big move, so you end up too far to punch back.",
      "Forgetting defense after your counter.",
    ],
    safetyNotes: [GENERAL_SAFETY, SOLO_DEFENSE],
    quiz: [
      {
        id: "defcounter-q1",
        question: "After you slip left, which punch is ready to throw?",
        options: ["The lead hook (3)", "The rear uppercut (6)", "None"],
        correctIndex: 0,
        explanation: "Slipping left puts weight on the front side, which loads the lead hook.",
      },
      {
        id: "defcounter-q2",
        question: "When should the counter come?",
        options: ["A few seconds later", "Straight after the defense", "Only after two defenses"],
        correctIndex: 1,
        explanation: "The opening only lasts a moment, while their punch is out or coming back.",
      },
    ],
    minutes: 4,
  },
  {
    id: "boxing-cutting-angles",
    sport: "boxing",
    level: 5,
    title: "Cutting Angles",
    summary: "Step to the side so you can hit and not be hit.",
    whatItIs: "You move off the straight line between you and the opponent, with a side step or a pivot, so they must turn to find you.",
    whenToUse: "After a combination, or when the opponent comes straight at you.",
    mechanics: [
      "After your combination, take a small side step or a pivot.",
      "Stay in your stance. Do not cross your feet.",
      "Face the target again straight away.",
      "Punch while the opponent is still turning to find you.",
    ],
    commonMistakes: [
      "Big steps that leave you off balance.",
      "Stepping to the side but not facing the target again.",
      "Always moving the same way, so it is easy to read.",
    ],
    safetyNotes: [GENERAL_SAFETY, CLEAR_SPACE],
    quiz: [
      {
        id: "angles-q1",
        question: "Why step to the side after a combination?",
        options: ["To rest", "So the opponent must turn to find you", "To get closer to the ropes"],
        correctIndex: 1,
        explanation: "From a new angle you can punch while their counter has to turn first.",
      },
    ],
    minutes: 3,
  },

  // ---------------- LEVEL 6: FIGHT IQ ----------------
  {
    id: "boxing-distance",
    sport: "boxing",
    level: 6,
    title: "Distance",
    summary: "Know when you are in range and when you are not.",
    whatItIs: "Distance is the space between you and the opponent. Long range is for the jab and cross, close range is for hooks and uppercuts.",
    whenToUse: "All the time. Step in to punch, step out when you are not punching.",
    mechanics: [
      "Use the jab to measure the distance.",
      "When you are not punching, stay just out of the opponent's reach.",
      "Step in to punch, then step out.",
      "Pick the punch for the range: straight punches far, hooks and uppercuts close.",
    ],
    commonMistakes: [
      "Standing in range and doing nothing.",
      "Reaching or jumping in from too far away.",
      "Throwing hooks from long range.",
    ],
    safetyNotes: [GENERAL_SAFETY, CLEAR_SPACE],
    quiz: [
      {
        id: "distance-q1",
        question: "Which punch is best at long range?",
        options: ["The jab", "The lead uppercut", "The rear hook"],
        correctIndex: 0,
        explanation: "The jab is your longest punch and the safest way to measure distance.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-feints-timing",
    sport: "boxing",
    level: 6,
    title: "Feints and Timing",
    summary: "Fake a punch, read the reaction, punch at the right moment.",
    whatItIs: "A feint is a fake punch that makes the opponent react. Timing means punching at the right moment, for example when the hands drop.",
    whenToUse: "Against careful opponents and counter punchers, to make them open up or react.",
    mechanics: [
      "Feint with a small move: a twitch of the shoulder or half a jab.",
      "Bring the hand back fast to guard.",
      "Watch the reaction: do the hands move, does the opponent step back?",
      "Punch into the opening you see.",
      "Change your rhythm. Do not punch on the same beat every time.",
    ],
    commonMistakes: [
      "Feinting with a big move that leaves you open.",
      "Feinting with no plan for what comes next.",
      "Always the same rhythm, so you are easy to read.",
    ],
    safetyNotes: [GENERAL_SAFETY],
    quiz: [
      {
        id: "feint-q1",
        question: "What is a feint?",
        options: ["A fake punch that makes the opponent react", "A very hard punch", "A way to block"],
        correctIndex: 0,
        explanation: "A feint draws a reaction you can use.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-counter-punching",
    sport: "boxing",
    level: 6,
    title: "Counter Punching",
    summary: "Make them miss, then make them pay.",
    whatItIs: "You let the opponent attack, defend with a small move, and hit back while they are open.",
    whenToUse: "Against opponents who attack a lot. Good counters: slip right then cross, pull back then cross, parry then cross, roll then 3, 2.",
    mechanics: [
      "Stay calm, with your eyes on the opponent.",
      "See the punch and defend with a small move.",
      "Counter as their punch misses or comes back.",
      "Back to guard after the counter, ready to defend again.",
    ],
    commonMistakes: [
      "Only waiting, and never attacking yourself.",
      "Defending without countering.",
      "Wild, big counters that leave you open.",
    ],
    safetyNotes: [GENERAL_SAFETY, SOLO_DEFENSE],
    quiz: [
      {
        id: "counter-q1",
        question: "When is the best moment to counter?",
        options: ["Before they move", "As their punch misses or comes back", "After they reset their guard"],
        correctIndex: 1,
        explanation: "While their hand is out or coming back, that side is open.",
      },
    ],
    minutes: 3,
  },
  {
    id: "boxing-ring-control",
    sport: "boxing",
    level: 6,
    title: "Ring Control",
    summary: "Stay in the centre and away from the ropes.",
    whatItIs: "Using your footwork to stay near the centre of the ring and keep away from the ropes and corners.",
    whenToUse: "All through a round. At home, imagine the edges of a ring around your space.",
    mechanics: [
      "Try to stay near the centre.",
      "When your back is near the ropes, move out with a side step or a pivot, not straight back.",
      "Do not back up in a straight line for long.",
      "Move forward behind your jab to take the centre back.",
    ],
    commonMistakes: [
      "Backing straight into the ropes or a corner.",
      "Circling with crossed feet.",
      "Chasing the opponent wildly.",
    ],
    safetyNotes: [GENERAL_SAFETY, CLEAR_SPACE],
    quiz: [
      {
        id: "ring-q1",
        question: "Your back is near the ropes. What do you do?",
        options: ["Keep backing up", "Side step or pivot out", "Stand still and cover up"],
        correctIndex: 1,
        explanation: "Moving sideways or pivoting gets you back to the centre. Backing up traps you.",
      },
    ],
    minutes: 3,
  },
];

export function getLesson(id: string): Lesson | undefined {
  return BOXING_LESSONS.find((l) => l.id === id);
}
